# Generated by Django 6.0.1 on 2026-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcard_dificuldade_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.PositiveIntegerField(),
        ),
    ]
